# Generated by Django 3.0.8 on 2021-03-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_auto_20210307_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='index',
            field=models.TextField(verbose_name='Індекс'),
        ),
        migrations.AlterField(
            model_name='product',
            name='instock',
            field=models.IntegerField(verbose_name='В наявності'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original',
            field=models.TextField(verbose_name='Оригінал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10000, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(max_length=60, verbose_name='Виробник'),
        ),
    ]
