# Generated by Django 3.0.8 on 2021-02-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_auto_20210209_1526'),
        ('cart', '0006_auto_20210208_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='part',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.Product2'),
        ),
    ]
